
/*
    This is a run once setup scrit to insert enumerated values into the database. It should be run once and then deleted to prevent duplicate entries in the database.
    It should be run only after the database has been created and the tables have been generated by the JPA entities. It should be run before any API calls are made to ensure that the necessary data is in place for the API to function correctly.
*/

insert into tblc2d1b107a6214854b77794869e260c79 (col17127604a30e483e808eb0de8dbaf599,col2d1b107a6214854b77794869e260c79) values
(1,'Active');
insert into tblc2d1b107a6214854b77794869e260c79 (col17127604a30e483e808eb0de8dbaf599,col2d1b107a6214854b77794869e260c79) values
(2,'Inactive');
insert into tblc2d1b107a6214854b77794869e260c79 (col17127604a30e483e808eb0de8dbaf599,col2d1b107a6214854b77794869e260c79) values
(3,'Pending');    
insert into tblc2d1b107a6214854b77794869e260c79 (col17127604a30e483e808eb0de8dbaf599,col2d1b107a6214854b77794869e260c79) values
(4,'Suspended');
insert into tblc2d1b107a6214854b77794869e260c79 (col17127604a30e483e808eb0de8dbaf599,col2d1b107a6214854b77794869e260c79) values
(5,'Terminated');
insert into tblc2d1b107a6214854b77794869e260c79 (col17127604a30e483e808eb0de8dbaf599,col2d1b107a6214854b77794869e260c79) values
(6,'On Leave');

insert into tbl50cbbfdb285741f4aaaab654824de37d (col7c58f73208714685b70bc4ec07ef553e,col9ec67ee267465db198115f810e700b) values
(1,'Hourly');
insert into tbl50cbbfdb285741f4aaaab654824de37d (col7c58f73208714685b70bc4ec07ef553e,col9ec67ee267465db198115f810e700b) values
(2,'Salaried');
insert into tbl50cbbfdb285741f4aaaab654824de37d (col7c58f73208714685b70bc4ec07ef553e,col9ec67ee267465db198115f810e700b) values
(3,'Contract');
insert into tbl50cbbfdb285741f4aaaab654824de37d (col7c58f73208714685b70bc4ec07ef553e,col9ec67ee267465db198115f810e700b) values
(4,'Commission');


insert into tbl0d2189587ccb42b0add466e1baacb334 (col774c4a5c9e24406b9570f26fdb2e0208) values                                 
('admin');

insert into tbl0d2189587ccb42b0add466e1baacb334 (col774c4a5c9e24406b9570f26fdb2e0208) values
('generalmanager'); -- documant and employee manager

insert into tbl0d2189587ccb42b0add466e1baacb334 (col774c4a5c9e24406b9570f26fdb2e0208) values
('documentmanager'); -- everything document

insert into tbl0d2189587ccb42b0add466e1baacb334 (col774c4a5c9e24406b9570f26fdb2e0208) values
('payrollmanager'); -- everythin employee


/*

    The following insert statement create aN admin login so that the api can be accessed

*/

insert into tbl6651fa10bc634af1946fd09c19543004 
(col265665ff52084b81a911bfc3c9a55cee,  --first name
col6ea3fe0a1d424174a712f54b12701982,  --last name
col5cf54160a7694658a306d51e6fce663a,  --middle name
col17127604a30e483e808eb0de8dbaf599,  -- employee status
col8054e99747404f09a57a528d1e4edcb7, -- date of hire
col92a0e9d0a5d40518ec6186831f4c833,  -- ssn
col7bf4a0bcca3d45adbb77f43bd8244ebf, -- te;ephone landlne
col200a17dfe4ba43eeba016ee91e0fab28, -- telephone cell
colca95d1a9fe89b40ee9dd04f88b95122ae, -- email
colbeb4fed78b184676ada90a36598a1546, -- title
col59de268d68e847769bdca0e7ba1da66d,  --company id
col267f74369670435b8e97633834c361af, --employee number
col7c58f73208714685b70bc4ec07ef553e  --ratetype
)
values('super','admin', '', 1, CURRENT_DATE, '000000000', '0000000000', '0000000000','','', 1, 'sa100',1);

--create master key to login to app
--password = xErxesi4@0r 
--uid = masterkey
insert into tbla9f232a1034d4b02b0efdaa295c2bd37 (
    cola9f22c10a045488c8b6ec289ad46f55a,  --username
    colde08b096ba774084846148ffb591d7b9,  --storeHash == xErxesi4@0r
    col2748f249a6814344bcf308aeaf8352fd,  --storedSalt
    col4295b1e1b2f64aeb94a65790155834df   --employee id
)
values('masterkey', 
'24846c0845b2a48c342506c55a62a2032e6bcb2b627b6987c38d9d11bf0229e0f96439dd7e5c2a3bc4d1f09649b9ca0e3095d16c34ca5b34431e49074a68aae8', 
'5fe5a8a71a4d1ead594cf1c07109fc03ea20e6b7d61c7bdf467da70690413e226a92babc04b22f95c4771ac6f566553dee9dad86ca46503346a5ef4c041cba156b257c67b4e483b558878afb022542b70190817283ac3382d15cab32da9b137c5df817cc51ba243dcc7f2609ba0fd2bfbeac3592ab432149caf35fc5239e5aa6',
1);


--assign admin  with master key to admin role
insert into tblk6dbf67825b01405cb4790d4c3bbdec8d(colc95ed5740f41457fb6fd5158c133343d, col2b9e79e605924d4fa08d2b5135549e6c)
values(1,1);